Add a database connection check for deb package

diff --git a/build/install/deb/debian/postinst b/build/install/deb/debian/postinst
--- a/build/install/deb/debian/postinst
+++ b/build/install/deb/debian/postinst
@@ -32,6 +32,19 @@ case "$1" in
 		args+=(-mysqlh "$DB_HOST" -mysqld "$DB_NAME" -mysqlu "$DB_USER" );
 		[ -n "$DB_PWD" ] && args+=(-mysqlp "$DB_PWD" );
 
+		command -v mysql >/dev/null 2>&1 || { echo "MySQL client not found"; exit 1; }
+		MYSQL="mysql -h$DB_HOST -u$DB_USER"
+		if [ -n "$DB_PWD" ]; then
+			MYSQL="$MYSQL -p$DB_PWD"
+		fi
+
+		$MYSQL -e ";" >/dev/null 2>&1
+		ERRCODE=$?
+		if [ $ERRCODE -ne 0 ]; then
+			systemctl mysql start >/dev/null 2>&1
+			$MYSQL -e ";" >/dev/null 2>&1 || { echo "Trying to establish MySQL connection... FAILURE"; exit 1; }
+		fi
+
 		db_get {{product}}/redis-host || true
 		REDIS_HOST="$RET"
 		db_get {{product}}/redis-port || true
